version: "3.8"
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        APP_ENV: ${APP_ENV}
    environment:
      APP_ENV: ${APP_ENV}
    ports:
      - "3001:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
    depends_on:
      - back
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
      args:
        APP_ENV: ${APP_ENV} # Passa o ambiente para o Dockerfile
    environment:
      APP_ENV: ${APP_ENV} # Define a variável no container
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
      - /app/node_modules
    depends_on:
      - database
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
