version: "3.8"
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        APP_ENV: ${APP_ENV}
        NEXT_PUBLIC_BACKEND_URL_FOR_CLIENT: ${NEXT_PUBLIC_BACKEND_URL_FOR_CLIENT}
        BACKEND_URL_FOR_SERVER: ${BACKEND_URL_FOR_SERVER}
    environment:
      APP_ENV: ${APP_ENV}
      NEXT_PUBLIC_BACKEND_URL_FOR_CLIENT: ${NEXT_PUBLIC_BACKEND_URL_FOR_CLIENT}
      BACKEND_URL_FOR_SERVER: ${BACKEND_URL_FOR_SERVER}
    ports:
      - "3001:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
    depends_on:
      - back
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
      args:
        APP_ENV: ${APP_ENV}
    environment:
      APP_ENV: ${APP_ENV}
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
      - /app/node_modules
    depends_on:
      - database
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
